app/models.py
from . import db
from flask_login import UserMixin
from . import login_manager
from werkzeug.security import generate_password_hash,check_password_hash

class Quote:
    def __init__(self,author,quote):
        self.author=author
        self.quote=quote


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__='users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255),index = True)
    email= db.Column(db.String(255),unique = True, index = True)
    pass_secure = db.Column(db.String(455))
    blogs=db.relationship('Blogs',backref='user',lazy='dynamic')
    
    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password, method='pbkdf2:sha256', salt_length=8)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    
    def __repr__(self):
        return f'User {self.username}'

class Blogs(db.Model):
    __tablename__='blogs'
    id = db.Column(db.Integer, primary_key=True)
    title=db.Column(db.String(255))
    description=db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    
 
    def __repr__(self):
        return self.title

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class Blog(FlaskForm):
    title=StringField('Enter the Title', validators=[DataRequired()])
    description= TextAreaField('Give brief description',validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_login import LoginManager
from flask_mail import Mail


login_manager = LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'

bootstrap=Bootstrap()
db=SQLAlchemy()
mail=Mail()

def create_app(config_name):
    app=Flask(__name__)

    app.config.from_object(config_options[config_name])

    #Initialization flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')

    return app 

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import render_template,url_for,abort,redirect
from flask_login import login_required
from . import main
from .. import db
from .forms import Blog
from ..models import User,Blogs
from ..request import get_quote

@main.route('/')
def index():
  random_quote=get_quote()

  user = User.query.filter_by(username='uname').first()
  blogs = Blogs.query.all()
  title = 'Welcome to Bloggy'
  message = 'Cool Blogs'
  return render_template('index.html',random_quote=random_quote, message = message,title= title,blogs=blogs, user=user)

@main.route('/user/<uname>',methods=['GET','POST'])
@login_required
def profile(uname):
  user = User.query.filter_by(username=uname).first()
  blogs=Blogs.query.filter_by(user_id=user.id)
  if user is None:
    abort(404)
  title = f'{user.username}'
  return render_template('profile/profile.html',title=title,user = user,blogs=blogs)

@main.route('/blogs/<uname>', methods=['GET','POST'])
@login_required
def blogs(uname):
  blog_form = Blog()
  user = User.query.filter_by(username = uname).first()
  if blog_form.validate_on_submit():
    blog = Blogs(title = blog_form.title.data, description = blog_form.description.data,user = user)
    db.session.add(blog)
    db.session.commit()
    return redirect(url_for('main.index'))
  title='blogs'
  return render_template('blog.html',title=title,blog_form=blog_form)

@main.route('/blogs/delete/<int:blog_id>')
def delete(blog_id):
    blog= Blogs.query.filter_by(id=blog_id).first()
    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for('main.index'))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block -->
{% include 'navbar.html'%} 
 {% block styles%}
 {{super()}}
 <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
 {%endblock%}
 {%block content%} {%endblock%}

app/templates/blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-3"> </div>
<div class="col-md-6">
    <h1>New blog</h1>
    <hr>

{{wtf.quick_form(blog_form)}}

</div>
<div class="col-md-3"></div>
</div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{%block content %}


<div class="container">
  <h1>Random Quote</h1>
  <blockquote class="blockquote">
  <p class="mb-0">{{random_quote.quote}}</p>
  <footer class="blockquote-footer">By<cite title="Source Title">{{random_quote.author}}</cite></footer>
</blockquote>
  

</div>
<div class="container-fluid home-container">
  <div class="container home-container">
  <h1 class="text-center">{{message}}</h1>
  <hr />
	<div class="row">
		<div class="col-md-12">
			<h2>Blogs</h2>
			<div class="row box">
				{% for blog in blogs %}
				<div class="col-sm-6">
					<ul class="list-unstyled">
						<li
							class="style"
							style="
								background-color: antiquewhite;
								min-height: 29rem;
								padding: 1.5rem;
								box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.2);
							"
						>
							<h3 class="text-primary">{{blog.title}}</h3>
							<h4>{{blog.description}}</h4>
							<p style="color: #ff5421">By: {{blog.user.username}}</p>
							<a><button class="btn btn-primary btn-sm">Comment</button></a>
							<a href="/blogs/delete/{{blog.id}}"
								><button class="btn btn-danger btn-sm">Delete</button></a
							>
						</li>
						<hr />
						<br />
					</ul>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

</div>

{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse sticky" style="border-radius:0;" role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Home</a>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('main.blogs',uname=current_user.username)}}">Add Blog</a></li>
            <li style="color:white;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
      </div>
  </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">
{% endblock %}
{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
</div>
</div>
  <h2 class='text-primary text-center'>Your Blogs</h2>
  <div class="row">
    {% for blog in blogs %}
    <div class="col-sm-6">
      <ul class='list-unstyled '>
        <li class='style'
        style="background-color: antiquewhite;height: 25rem;padding: 1.5rem;box-shadow: 0 .5rem 1rem rgba(0, 0,0,.2);">
          <h3 class='text-primary'>{{blog.title}}</h3>
          <h4>{{blog.description}}</h4>
        </li> <hr> <br>
        </ul>
    </div>

    {% endfor %}
  </div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block
content %}
<div class="container post-form">{{wtf.quick_form(form)}}</div>
{% endblock %}